### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by PyRO69** [aakshintala/cpplox#1]
- Use  `#pragma once` only. Don't `IFDEF` too. 
- `/src` should contain only your `cpp` files. You can be more modular in breaking up the project early on.
- Don't define constructors inline.
- Add documentation to your headers!
- A bunch of private utility methods in class `Scanner` can be moved to an anonymous namespace in the implementation file and you don't need to expose those in the header at all.
- Use `enum class`.
- `StatusCodes` has very little to do with the same.
- Why not store floating point literals as strings when you encounter them? You're converting back to string multiple times and that's not efficient.
- In method `TokenTypeString` you need to check that your find returns a valid iterator before de-referencing.

**Comment by aakshintala** [comment]
Thanks! Will make code changes in the evening. 
Some clarifications/discussion:

1. `#pragma once` isn't standard though right? Both the google cpp style guide and the cpp standard guide say do not use `pragma once`; use only `#ifdefs`. I like the pragma (for the very slight compilation speedup) so decided to use both.

2. Hmmm, I like to keep only the public API in the include folder (in my case the headers for libcpplox), and restrict internal headers to src. What do you mean by being more modular? A separate directory for each component (so say a separate library for scanner, and another for parser, etc.?

3. Hmmm, could you explain what the downsides are? Or is this a style thing (maybe more readable if all of the implementation is in a .cpp file?) Even for constructors that only use an initializer list?

4. Right.

5. Ah, clever! Didn't think of that at all. Will do.

6. Is there a difference between the two? Assuming there isn't, why class over struct? Convention?

7.  File started out containing only `LoxStatus` and then evolved to include the `ErrorReporter` class. Will change to `ErrorReporter.h` cos that's more descriptive.

8. Ah! Good catch! Presumably, the way to do this would be with a struct wrapping the double and the string?

9. 👍🏽

**Comment by aakshintala** [comment]
Regarding #5, most of the private functions in `Scanner` touch member data. Given functions in an internal namespace won't be able to access these private data, I don't understand how this would work?

**Comment by PyRO69** [comment]
For #5, make them free functions and accept whatever you need as arguments.

**Comment by PyRO69** [comment]
Onto the discussion,

- Yeah most compilers today support `#pragma once` so unless you're wanting this to be portable even on some obscure hardware, don't bother. That said, it is more rigorous to use `IFDEF`s. I guess it is a style thing so treat that as a nit.
- In that case, what you want in your include is a limited interface. Maybe use a PIMPL style solution and hide all implementation details in a `impl` directory. And yeah making it modular early on so you can isolate test and evolve each component easily. You can create all the directories you want. Break up every namespace into a directory :)
- Keeping your headers clean is nice. Your library users will thank you for it. Just cleaner I think. Again we're in style territory. Feel free to play devil's advocate :D 
- Lol
- We covered 5.
- Identical. You want to keep enums scoped almost always. `class` is more common I suppose.
- Makes sense.
- Yeah that would work. Or just a `std::pair`.
- 👍

**Comment by aakshintala** [comment]
I've split up most of the headers that had code and moved implementations into cpp files. I've also cleaned up most of the header files so that there aren't any unnecessary includes in them.

For now, I'm going to leave modularization alone. I'll probably break the code up into multiple libraries once I know more about the layout of things... But thanks for that note. Will keep it in mind.

Made most of the changes you suggested. Thanks!
